version: '3.4'

services:
  cadastroproduto:
    image: api-cadastroproduto
    container_name: cadastroProduto
    build:
      context: .
      dockerfile: CadastroProduto\Dockerfile
    ports:
    - "5010:5010"
    depends_on:
      - sqlserver
    networks:
        rederefit:
         ipv4_address: 172.18.0.5